import { useEffect, useState } from 'react'
import { Alert, Button, Card, CardContent, Container, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { listBudgets, createBudget, deleteBudget, getBudgetSummary } from '../../api'
import { hasPremiumAccess, PremiumLocked } from '../premium'
import { getUserGroupsService } from '../../services/groupServices'

export default function Budget() {
  const profile = JSON.parse(localStorage.getItem('profile') || '{}')
  const [groups, setGroups] = useState([]); const [groupId, setGroupId] = useState(''); const [budgets, setBudgets] = useState([]); const [summary, setSummary] = useState(null); const [error, setError] = useState('')
  const [form, setForm] = useState({ name: 'Monthly Budget', amount: '', currency: 'INR', categoryText: '', startDate: new Date().toISOString().slice(0, 10), endDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().slice(0, 10) })
  useEffect(() => { if (hasPremiumAccess(profile)) getUserGroupsService(profile).then(r => setGroups(r?.data?.groups || [])) }, [])
  useEffect(() => { if (groupId) listBudgets(groupId).then(r => setBudgets(r.data.budgets || [])).catch(e => setError(e.response?.data?.message || 'Unable to load budgets')) }, [groupId])
  if (!hasPremiumAccess(profile)) return <Container><PremiumLocked /></Container>
  const save = async e => { e.preventDefault(); try { const categoryBudgets = form.categoryText.split(',').filter(Boolean).map(item => { const [category, amount] = item.split(':'); return { category: category.trim(), amount: Number(amount) } }); const r = await createBudget({ ...form, groupId, categoryBudgets }); setBudgets([r.data.budget, ...budgets]); setError('') } catch (e) { setError(e.response?.data?.message || 'Unable to save budget') } }
  const remove = async id => { try { await deleteBudget({ budgetId: id, groupId }); setBudgets(budgets.filter(b => b._id !== id)) } catch (e) { setError(e.response?.data?.message || 'Unable to delete budget') } }
  const showSummary = async id => { try { const r = await getBudgetSummary({ budgetId: id, groupId }); setSummary(r.data.summary) } catch (e) { setError(e.response?.data?.message || 'Unable to calculate summary') } }
  return <Container><Typography variant="h3" gutterBottom>Budget Management</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<TextField select fullWidth label="Group" value={groupId} onChange={e => setGroupId(e.target.value)} sx={{ mb: 3 }}>{groups.map(g => <MenuItem value={g._id} key={g._id}>{g.groupName}</MenuItem>)}</TextField><Card><CardContent><Typography variant="h5" gutterBottom>Create a budget</Typography><Stack component="form" onSubmit={save} direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField label="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><TextField label="Amount" type="number" required value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /><TextField label="Category budgets" helperText="Food:5000,Travel:3000" value={form.categoryText} onChange={e => setForm({ ...form, categoryText: e.target.value })} /><TextField select label="Currency" value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}><MenuItem value="INR">INR</MenuItem><MenuItem value="USD">USD</MenuItem><MenuItem value="EUR">EUR</MenuItem></TextField><TextField label="Start" type="date" InputLabelProps={{ shrink: true }} value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })} /><TextField label="End" type="date" InputLabelProps={{ shrink: true }} value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })} /><Button type="submit" variant="contained" disabled={!groupId}>Save</Button></Stack></CardContent></Card><Grid container spacing={2} sx={{ mt: 2 }}>{budgets.map(b => <Grid item xs={12} md={6} key={b._id}><Card><CardContent><Typography variant="h6">{b.name}</Typography><Typography>{b.amount} {b.currency}</Typography><Button onClick={() => showSummary(b._id)} sx={{ mt: 1 }}>View spending</Button><Button color="error" onClick={() => remove(b._id)} sx={{ mt: 1, ml: 1 }}>Delete</Button></CardContent></Card></Grid>)}</Grid>{summary && <Card sx={{ mt: 3 }}><CardContent><Typography variant="h5">Budget summary</Typography><Typography>{summary.spent.toFixed(2)} spent · {summary.remaining.toFixed(2)} remaining</Typography><Typography>{summary.percentageUsed.toFixed(2)}% used · {summary.status}</Typography><Typography sx={{ mt: 1 }}>Top category: {Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1])[0]?.[0] || 'No expenses yet'}</Typography></CardContent></Card>}</Container>
}
